const $=s=>document.querySelector(s);let filter="ALL",favOnly=false;
const icons={Sports:"🏈",Racing:"🏎️",Wave:"🌊",Arcade:"🕹️",Space:"🚀",Puzzle:"🧩",Action:"⚔️"};
$("#catbar").innerHTML=[["ALL","🎮"],...Object.entries(icons)].map(([n,i])=>`<button class="cat ${n==="ALL"?"active":""}" data-c="${n}">${i} ${n}</button>`).join("");
document.querySelectorAll(".cat").forEach(b=>b.onclick=()=>{document.querySelectorAll(".cat").forEach(x=>x.classList.remove("active"));b.classList.add("active");filter=b.dataset.c;draw()});
const fav=id=>localStorage.getItem("fav"+id)==="1",best=id=>localStorage.getItem("best"+id)||0;
function draw(){let q=$("#search").value.toLowerCase(),a=GAMES.filter(g=>(filter==="ALL"||g.category===filter)&&g.name.toLowerCase().includes(q)&&(!favOnly||fav(g.id)));$("#count").textContent=a.length+" GAMES";$("#grid").innerHTML=a.map(g=>`<article class="card" data-id="${g.id}"><div class="art"><small>${g.category}</small><span>${g.icon}</span>${fav(g.id)?'<b class="star">★</b>':''}</div><div class="body"><h3>${g.name}</h3><p>Original ${g.category.toLowerCase()} mini-game.</p><span class="best">BEST ${best(g.id)}</span></div></article>`).join("");document.querySelectorAll(".card").forEach(c=>c.onclick=()=>launch(+c.dataset.id))}
$("#search").oninput=draw;$("#fav").onclick=()=>{favOnly=!favOnly;draw()};$("#random").onclick=()=>launch(GAMES[Math.floor(Math.random()*GAMES.length)].id);$("#close").onclick=close;$("#modal").onclick=e=>{if(e.target.id==="modal")close()};function close(){$("#modal").hidden=true;$("#mount").innerHTML=""}
function launch(id){let g=GAMES.find(x=>x.id===id);$("#modal").hidden=false;$("#mount").innerHTML=`<div class="game"><h2>${g.icon} ${g.name}</h2><p>${g.category} • Arrows/WASD move • SPACE special action.</p><div class="hud" id="hud"></div><canvas id="canvas" width="880" height="460"></canvas><div class="touch"><button onclick="press('ArrowLeft')">←</button><button onclick="press(' ')">ACTION</button><button onclick="press('ArrowRight')">→</button></div></div>`;start(g)}
function press(k){window.dispatchEvent(new KeyboardEvent("keydown",{key:k,code:k===" "?"Space":k}))}
function start(g){const c=$("#canvas"),x=c.getContext("2d"),hud=$("#hud"),W=c.width,H=c.height;let keys={},score=0,over=false,t=0,p={x:W/2,y:H-75};let obs=Array.from({length:9},(_,i)=>({x:40+Math.random()*800,y:-i*100,s:25+Math.random()*35,v:2+Math.random()*3}));
const down=e=>{keys[e.key]=1;if(e.code==="Space"||e.key===" "){if(g.name.startsWith("Escape Road")){p.y-=20;p.x+=(Math.random()>.5?35:-35)}else score+=5}},up=e=>keys[e.key]=0;addEventListener("keydown",down);addEventListener("keyup",up);
function loop(){t++;x.fillStyle="#080812";x.fillRect(0,0,W,H);
if(g.name.startsWith("Escape Road")){x.fillStyle="#181826";x.fillRect(170,0,540,H);x.strokeStyle="#ffe76b";x.lineWidth=5;x.setLineDash([30,30]);x.lineDashOffset=-t*4;x.beginPath();x.moveTo(440,0);x.lineTo(440,H);x.stroke();x.setLineDash([]);if(!over){if(keys.ArrowLeft||keys.a)p.x-=7;if(keys.ArrowRight||keys.d)p.x+=7;p.x=Math.max(205,Math.min(675,p.x));score++;if(g.name==="Escape Road 2"&&t%90===0)score+=25}obs.forEach((o,i)=>{o.y+=o.v+(g.name==="Escape Road 2"?1.3:0);if(o.y>H+60){o.y=-60;o.x=215+Math.random()*430;score+=5}x.fillStyle=i%3===0?"#28e8ff":"#ff3b63";x.fillRect(o.x-o.s/2,o.y-o.s/2,o.s,o.s*1.5);if(Math.abs(o.x-p.x)<o.s&&Math.abs(o.y-(H-75))<55)over=true});x.fillStyle="#baff45";x.fillRect(p.x-21,H-110,42,62);if(g.name==="Escape Road 2"){x.fillStyle="#ff39b9";x.fillRect(230,28,Math.min(410,score/5),7)}}
else{let bg={Sports:"#10331f",Racing:"#111b32",Wave:"#15104a",Arcade:"#32102f",Space:"#080b25",Puzzle:"#17211a",Action:"#2b1515"}[g.category];x.fillStyle=bg;x.fillRect(0,0,W,H);if(!over){if(keys.ArrowLeft||keys.a)p.x-=6;if(keys.ArrowRight||keys.d)p.x+=6;if(keys.ArrowUp||keys.w)p.y-=5;if(keys.ArrowDown||keys.s)p.y+=5;p.x=Math.max(25,Math.min(W-25,p.x));p.y=Math.max(25,Math.min(H-25,p.y));score++}for(let i=0;i<14;i++){x.fillStyle=i%2?"#ff39b9":"#28e8ff";x.fillRect((i*71+t*2)%W,(i*43+t)%H,18,18)}x.fillStyle="#baff45";x.fillRect(p.x-18,p.y-18,36,36)}
hud.innerHTML=`<span>${g.name} • ${score}</span><span>${over?"GAME OVER — ENTER":"BEST "+best(g.id)}</span>`;if(over&&keys.Enter){score=0;over=false}if(score>+best(g.id))localStorage.setItem("best"+g.id,score);requestAnimationFrame(loop)}loop()}
draw();